name: Build LaTeX document

on:
  push:
    branches: [master]

jobs:
  build-latex:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build LaTeX document
        uses: https://github.com/xu-cheng/latex-action@v3
        with:
          texlive_version: latest
          extra_packages: inkscape
          latexmk_shell_escape: true
          root_file: thesis.tex
      - name: Rename document
        run: mv thesis.pdf facial-animation-using-inverse-kinematics.pdf
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: facial-animation-using-inverse-kinematics.pdf
