name: Build LaTeX document

on:
  push:
    branches: [master]

jobs:
  build-latex:
    runs-on: texlive-latest
    steps:
      - name: Setup node for checkout
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build LaTeX document
        run: latexmk -shell-escape -pdf thesis.tex
      - name: Rename document
        run: mv thesis.pdf facial-animation-using-inverse-kinematics.pdf
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: pdf
          path: facial-animation-using-inverse-kinematics.pdf
